### ISSUE TITLE
Source code no longer available

### ISSUE THREAD

**Issue by Baytars** [stefan-reich/StefansOS#1]
The domain tinybrain.de doesn't seem to be hosting any source code any more. Would you please upload your source code on Github? Many thanks!

**Comment by stefan-reich** [comment]
Hi! Yeah it's gone... didn't want to be "tiny" anymore :)

Source code is now here: http://code.botcompany.de/1024932

Uploading to GitHub is a lot of hassle and I'm not sure what the purpose would be...

**Comment by Baytars** [comment]
Thank you for your work! It's awesome anyway!

**Comment by stefan-reich** [comment]
Thanks :) It will be great if we can make it more accessible to new users at some point. Even the download page is a bit hidden right now. And the welcome screen doesn't really do much. Even though you can through "Modules > Other module..." always add any module from the repo.

Anything particular you are interested in? Many greetings
